Get command-line arguments working (for directory)
bean00/http-server pull request #9
Opened 2018-02-15 00:21 UTC by bean00

The constructor in `ArgParser` should be cleaned up. I can extract out the body into a method, and keep extracting out methods, but I also want to see if I can use some functional programming here to clean it up. Feel free to offer suggestions here.

Right now for my `DriverTest` I don't test the regular program execution (where the server just starts and runs). I tried writing that test first, but my program went into an infinite loop (due to the `while(true)`). I was considering adding an optional command-line argument that has the server run only one iteration of the loop, but I decided to just focus on testing the `IllegalArgumentException` (and leave the normal case for Cob Spec to test).

2018-02-15 01:35 UTC, jdesrosiers requested changes
Your ArgParser has a bug. Add a test to expose it.

I like that you are trying to organize your code better into packages, but you need better names than `helpers` and `exceptions`.

2018-02-15 18:03 UTC, jdesrosiers requested changes
OK, you squashed the bug, but ArgParser still needs a lot of cleanup. (Especially a quite a bit of unnecessary code)

Also, add `constant` to the list of package names that are not good enough.

2018-02-16 02:51 UTC, jdesrosiers approved these changes

2018-02-19 17:59 UTC, tbaik approved these changes

2018-02-19 18:56 UTC, merged